image: node:8

.scripting: &utils |
  function setup_npm_token() {
    echo "//npmjs.artifacts.zxteam.net/:_authToken=$NPM_TOKEN" >> ~/.npmrc
  }
  function verify_package_version() {
    local PACKAGE_VERSION=$(awk '/version/{gsub(/("|",)/,"",$2);print $2};' package.json)
    echo "Tag $CI_COMMIT_REF_NAME . Package $PACKAGE_VERSION"
    if [ $PACKAGE_VERSION != $CI_COMMIT_REF_NAME ]; then
      echo "Package version ${PACKAGE_VERSION} is not same as tag version ${CI_COMMIT_REF_NAME}" >&2
      exit 255
    fi
  }

stages:
  - build
  - publish

build:
  stage: build
  artifacts:
    expire_in: 5 mins
    untracked: false
    paths:
      - .dist/
      - .package/
      - src/**/*.d.ts
      - src/**/*.js
      - src/**/*.map
    when: on_success
  before_script:
    - npm install --progress=false
  script:
    - npm run build

pages:
  stage: publish
  dependencies:
    - build
  script:
    - mkdir -p "public/$CI_COMMIT_REF_SLUG"
    - echo "CI_PROJECT_NAMESPACE = $CI_PROJECT_NAMESPACE" >> "public/$CI_COMMIT_REF_SLUG/build.log"
    - echo "CI_COMMIT_REF_SLUG = $CI_COMMIT_REF_SLUG" >> "public/$CI_COMMIT_REF_SLUG/build.log"
    - env >> "public/$CI_COMMIT_REF_SLUG/build.log"
    - echo >> "public/$CI_COMMIT_REF_SLUG/build.log"
    - echo "See log file http://$CI_PROJECT_NAMESPACE.pages.dev.zxteam.net/$CI_PROJECT_NAME/$CI_COMMIT_REF_SLUG/build.log"
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master
    - dev

publish to npmjs.artifacts.zxteam.net:
  stage: publish
  dependencies:
    - build
  before_script:
    - *utils
    - verify_package_version
    - setup_npm_token
  script:
    - cd .dist && npm publish --access=public
  only:
    - tags
